_RAW = [
    # h3=0 Capacetes
    ( 0,   0, "Harlequinn's Crest", "Satanic"),
    ( 0,   1, "The Colossal Avenger", "Heroic"),
    ( 0,   2, "Demon Warlord's Helm", "Satanic"),
    ( 0,   3, "The Bucket", "Satanic"),
    ( 0,   4, "Sky Crusader Helm", "Satanic"),
    ( 0,   5, "Helm of Dominator", "Satanic"),
    ( 0,   6, "The Faceless Priest", "Satanic"),
    ( 0,   7, "Uabel's Helmet", "Set"),
    ( 0,   8, "Reaper's Hood", "Set"),
    ( 0,   9, "Genji's Battle Helmet", "Set"),
    ( 0,  10, "Mevius' Mighty Helmet", "Set"),
    ( 0,  11, "Flame God's Helmet", "Satanic"),
    ( 0,  12, "Ice King's Crown", "Satanic"),
    ( 0,  13, "Zeus' Circlet", "Set"),
    ( 0,  14, "Redneck's Cap", "Set"),
    ( 0,  15, "Pirate Captain's Hat", "Set"),
    ( 0,  16, "Death Lord's Crown", "Set"),
    ( 0,  17, "Thor's Battle Cap", "Set"),
    ( 0,  18, "Viking's Sacred Helmet", "Set"),
    ( 0,  19, "Nomad's Sand Bandana", "Set"),
    ( 0,  20, "Nobunaga's Battle Helmet", "Set"),
    ( 0,  21, "Gladiator's Skullet", "Set"),
    ( 0,  22, "Doctor's Visage", "Set"),
    ( 0,  23, "Aztec Crown", "Set"),
    ( 0,  24, "Wendigo Skull", "Set"),
    ( 0,  25, "Judge, Jury & Executioner", "Satanic"),
    ( 0,  26, "Death Knight's Visage", "Satanic"),
    ( 0,  27, "Ancient Avenger", "Satanic"),
    ( 0,  28, "Burning Gaze", "Satanic"),
    ( 0,  29, "Sight Of The Gods", "Heroic"),
    ( 0,  30, "Zealot's Guise of Doom", "Set"),
    ( 0,  31, "Flame Diviner's Refuge", "Set"),
    ( 0,  32, "Lumberjack's Safety Helm", "Set"),
    ( 0,  33, "Blood-letter's Crown", "Set"),
    ( 0,  34, "Venom's Skull", "Set"),
    ( 0,  35, "Shield Bearer's Crown", "Set"),
    ( 0,  36, "Juggernaut's Siege Helm", "Set"),
    ( 0,  37, "Lost Master's Vision", "Set"),
    ( 0,  38, "Valkyrie's Winged Helm", "Set"),
    ( 0,  39, "Surgical Mask", "Satanic"),
    ( 0,  40, "Battle Worn Visor", "Set"),
    ( 0,  41, "Underworld's Skullbreaker", "Satanic"),
    ( 0,  42, "Sand Traveler's Guise", "Satanic"),
    ( 0,  43, "Guise of the Dead", "Satanic"),
    ( 0,  44, "Veil of Mystery", "Satanic"),
    ( 0,  45, "Crown of the North", "Satanic"),
    ( 0,  46, "Tenebris' Grievance", "Satanic"),
    ( 0,  47, "Mask of the Beyond", "Satanic"),
    ( 0,  48, "Pit Lord's Vanquisher", "Satanic"),
    ( 0,  49, "Lava King's Lost Mask", "Heroic"),
    ( 0,  50, "The Grand Champion", "Satanic"),
    ( 0,  51, "Crown of Midnight", "Satanic"),
    ( 0,  52, "Nikita's KJ-33 Helmet", "Heroic"),
    ( 0,  53, "The Curator of Secrets", "Satanic"),
    ( 0,  54, "Sheep King's Crown", "Set"),
    ( 0,  55, "Warlord's Fury", "Satanic"),
    ( 0,  56, "Witches Brimmed Hat", "Satanic"),
    ( 0,  57, "Assassin's Hood", "Satanic"),
    ( 0,  58, "Knight Captain's Helmet", "Satanic"),
    ( 0,  59, "Chronomancer's Observance", "Set"),
    ( 0,  60, "Sand Manipulator's Mask", "Set"),
    ( 0,  61, "Ymir's Frozen Shroud", "Set"),
    ( 0,  62, "Einar's Horned Helmet", "Set"),
    ( 0,  63, "Gabriel's Brimmed Fedora", "Set"),
    ( 0,  64, "Grimbone's Visage", "Heroic"),
    ( 0,  65, "Odin's Eternal Visage", "Set"),
    ( 0,  66, "Aetherweaver's Veil", "Satanic"),
    ( 0,  67, "Sentinel's Headguard", "Satanic"),
    ( 0,  68, "Executioner's Headplate", "Satanic"),
    ( 0,  69, "Bloodthirster's Warhelm", "Satanic"),
    ( 0,  70, "Mage's Starshroud", "Satanic"),
    ( 0,  71, "Reaver's Headplate", "Satanic"),
    ( 0,  72, "Juda's Broken Halo", "Satanic"),
    ( 0,  73, "Solar Prophet's Crown", "Set"),
    ( 0,  74, "Lunar Prophet's Tiara", "Set"),
    ( 0,  75, "Harlequinn's Veil", "Heroic"),
    ( 0,  76, "Butcher's Hood", "Set"),
    ( 0,  77, "Gabriel's Dauntless Vision", "Heroic"),
    ( 0,  78, "Thunder Caller's Veil", "Set"),
    ( 0,  79, "High Roller's Deathcrown", "Heroic"),
    ( 0,  80, "Gaze of the Oblivion", "Heroic"),
    ( 0,  81, "Eternal Death", "Heroic"),
    ( 0,  82, "Metal Vocalist's Leather Mask", "Set"),
    ( 0,  83, "Dragon Knight's Helmet", "Heroic"),
    ( 0,  84, "Crown of Doom", "Heroic"),
    ( 0,  85, "Lucifer's Crown", "Angelic"),
    ( 0,  86, "Mask of the Celestial", "Angelic"),
    ( 0,  87, "Veil of Consecration", "Satanic"),
    ( 0,  88, "Face of Existence", "Heroic"),
    # h3=1 Peitorais
    ( 1,   0, "Heaven's Might", "Satanic"),
    ( 1,   1, "Leviathan's Carcass", "Satanic"),
    ( 1,   2, "Tayrel's Chestplate", "Angelic"),
    ( 1,   3, "Uabel's Chest", "Set"),
    ( 1,   4, "Marsh Shroud", "Satanic"),
    ( 1,   5, "Gladiator's Demise", "Satanic"),
    ( 1,   6, "Hellfire Cuirass", "Satanic"),
    ( 1,   7, "Devil's Cocoon", "Satanic"),
    ( 1,   8, "Mevius' Mighty Plate", "Set"),
    ( 1,   9, "Anubis Torso", "Set"),
    ( 1,  10, "Genji's Battle Armor", "Set"),
    ( 1,  11, "Satan's Cuirass", "Set"),
    ( 1,  12, "Sand King's Scarab", "Satanic"),
    ( 1,  13, "Ice Howl's Cuirass", "Satanic"),
    ( 1,  14, "Grandwizard's Robe", "Satanic"),
    ( 1,  15, "Zeus' Body Armor", "Set"),
    ( 1,  16, "Redneck's Shirt", "Set"),
    ( 1,  17, "Pirate Captain's Shirt", "Set"),
    ( 1,  18, "Death Lord's Bone Armor", "Set"),
    ( 1,  19, "Thor's Chest Armor", "Set"),
    ( 1,  20, "Cuirass of Blood", "Satanic"),
    ( 1,  21, "Magister's Robe", "Satanic"),
    ( 1,  22, "Nomad's Battlerobe", "Set"),
    ( 1,  23, "Marksman's Hunting Shroud", "Set"),
    ( 1,  24, "Upi's Sweetshirt", "Satanic"),
    ( 1,  25, "Thunder Gladiator's Armor", "Satanic"),
    ( 1,  26, "Nobunaga's Battle Cuirass", "Set"),
    ( 1,  27, "Dante's Jacket", "Set"),
    ( 1,  28, "Lancer's Chestplate", "Set"),
    ( 1,  29, "Demon's Ribcage", "Set"),
    ( 1,  30, "Sacred Robe", "Set"),
    ( 1,  31, "Chestplate of Fire", "Set"),
    ( 1,  32, "Lichbane", "Satanic"),
    ( 1,  33, "St. Jupe's Plate of Command", "Angelic"),
    ( 1,  34, "Traveler's Leather Jacket", "Set"),
    ( 1,  35, "Gem King's Garb", "Heroic"),
    ( 1,  36, "Engineer's Plated Vest", "Set"),
    ( 1,  37, "Vagabond's Wraps", "Set"),
    ( 1,  38, "Flame Diviner's Sanctum", "Set"),
    ( 1,  39, "Blood-letter's Plate Body", "Set"),
    ( 1,  40, "Venom's Ribcage", "Set"),
    ( 1,  41, "Shield Bearer's Plated Armor", "Set"),
    ( 1,  42, "Juggernaut's Glorious Plate", "Set"),
    ( 1,  43, "Justiciar's Thunder Armor", "Set"),
    ( 1,  44, "Lost Master's Platemail", "Set"),
    ( 1,  45, "Earth Shaper's body", "Set"),
    ( 1,  46, "Plunderer's Jacket", "Set"),
    ( 1,  47, "Valkyrie's Battle Raiment", "Set"),
    ( 1,  48, "Hazmat Suit", "Satanic"),
    ( 1,  49, "Molten Steel Cataphract", "Satanic"),
    ( 1,  50, "Tropical Storm", "Satanic"),
    ( 1,  51, "Magic-Imbued Frozen Plate", "Satanic"),
    ( 1,  52, "Zephy's Gown", "Satanic"),
    ( 1,  53, "Mystique Allure", "Satanic"),
    ( 1,  54, "Cocoon of the Berserker", "Satanic"),
    ( 1,  55, "Giant Thorned Lizard Skin", "Satanic"),
    ( 1,  56, "Noxious Hunter's Reward", "Heroic"),
    ( 1,  57, "Empire's Military Plate", "Satanic"),
    ( 1,  58, "Leather Muscle Breastplate", "Satanic"),
    ( 1,  59, "Tundra Hunter's Long Coat", "Heroic"),
    ( 1,  60, "Arcane Robes of Authority", "Satanic"),
    ( 1,  61, "Thunder Guardian's Plate", "Heroic"),
    ( 1,  62, "Tactical Flak Jacket", "Set"),
    ( 1,  63, "Unearthed Esoteric Panoply", "Satanic"),
    ( 1,  64, "Sheep King's Hide", "Set"),
    ( 1,  65, "Clan Leader's Pride", "Satanic"),
    ( 1,  66, "Elementalist's Silk Shroud", "Satanic"),
    ( 1,  67, "Bandit Lord's Shroud", "Satanic"),
    ( 1,  68, "Black Knight's Carapace", "Satanic"),
    ( 1,  69, "Behemoth's Damascus Body", "Satanic"),
    ( 1,  70, "Sand Manipulator's Kalasiris", "Set"),
    ( 1,  71, "Ymir's Frozen Vestment", "Set"),
    ( 1,  72, "Einar's Plated Armor", "Set"),
    ( 1,  73, "Gabriel's Leather Trench Coat", "Set"),
    ( 1,  74, "Grimbone's Ribcage", "Heroic"),
    ( 1,  75, "Odin's Battlearmor", "Set"),
    ( 1,  76, "Ironclad Protector", "Satanic"),
    ( 1,  77, "Magiward Battlegear", "Satanic"),
    ( 1,  78, "Wardbreaker Armor", "Satanic"),
    ( 1,  79, "Aegisweave Robes", "Satanic"),
    ( 1,  80, "Solar Prophet's Robes", "Set"),
    ( 1,  81, "Stoneplate of Corruption", "Heroic"),
    ( 1,  82, "Butcher's Apron", "Set"),
    ( 1,  83, "Gabriel's Broken Wings", "Heroic"),
    ( 1,  84, "Thunder Caller's Robe", "Set"),
    ( 1,  85, "Muspelheim Guardian's Scorched Plate", "Heroic"),
    ( 1,  86, "Venomsteel Carapace", "Heroic"),
    ( 1,  87, "Isarius Ironthorn Breastplate", "Heroic"),
    ( 1,  88, "Executioner's Cocoon", "Heroic"),
    ( 1,  89, "Exiled Pagan's Mantle", "Satanic"),
    ( 1,  90, "Runemaster's Mantle", "Satanic"),
    ( 1,  91, "Glacial Gladiator's Armor", "Satanic"),
    ( 1,  92, "Magma Gladiator's Armor", "Satanic"),
    ( 1,  93, "Scourge Gladiator's Armor", "Satanic"),
    ( 1,  94, "Arcane Gladiator's Armor", "Satanic"),
    ( 1,  95, "Grand Arch Wizard's Mantle", "Unholy"),
    ( 1,  96, "Pit Fighter's Band Shirt", "Set"),
    ( 1,  97, "Dragon Knight's Vanguard", "Heroic"),
    ( 1,  98, "Wraith's Cloak", "Heroic"),
    ( 1,  99, "Arcanist's Wrath", "Heroic"),
    ( 1, 100, "Sharpshooter's Cloak", "Heroic"),
    ( 1, 101, "Prophet's Shroud", "Set"),
    ( 1, 102, "Skinwalker's Mantle", "Set"),
    # h3=2 Botas
    ( 2,   0, "Darkhide Boots", "Satanic"),
    ( 2,   1, "Tundra Marchers", "Satanic"),
    ( 2,   2, "Tribal Boots", "Satanic"),
    ( 2,   3, "Wizard Boots", "Satanic"),
    ( 2,   4, "Mevius' Mighty Marchers", "Set"),
    ( 2,   5, "Molten Boots", "Satanic"),
    ( 2,   6, "Frozen Marchers", "Satanic"),
    ( 2,   7, "Zeus' Battle Boots", "Set"),
    ( 2,   8, "Redneck's Working Boots", "Set"),
    ( 2,   9, "Pirate Captain's Boots", "Set"),
    ( 2,  10, "Death Lord's Marchers", "Set"),
    ( 2,  11, "Viking's Sacred Boots", "Set"),
    ( 2,  12, "Boots of Blood", "Satanic"),
    ( 2,  13, "Hermes Boots", "Satanic"),
    ( 2,  14, "Treasure Hunter's Boots", "Satanic"),
    ( 2,  15, "Gladiator's Battle Sandals", "Set"),
    ( 2,  16, "Dante's Boots", "Set"),
    ( 2,  17, "Sacred Marchers", "Set"),
    ( 2,  18, "Boots of Wild", "Set"),
    ( 2,  19, "Flaming Marchers", "Set"),
    ( 2,  20, "Mos'Arathim Marchers", "Satanic"),
    ( 2,  21, "Vagabond's Marchers", "Set"),
    ( 2,  22, "Bone Conjurer's Marchers", "Set"),
    ( 2,  23, "Lumberjack's Forestry Boots", "Set"),
    ( 2,  24, "Blood-letter's Plated Boots", "Set"),
    ( 2,  25, "Shield Bearer's Greaves", "Set"),
    ( 2,  26, "Juggernaut's Victory Marchers", "Set"),
    ( 2,  27, "Justiciar's Thunder Boots", "Set"),
    ( 2,  28, "Lost Master's Marchers", "Set"),
    ( 2,  29, "Earth Shaper's Boots", "Set"),
    ( 2,  30, "Plunderer's Deck Marchers", "Set"),
    ( 2,  31, "Battle Worn Boots", "Set"),
    ( 2,  32, "Steadfast Marchers", "Satanic"),
    ( 2,  33, "Spiked Greaves", "Satanic"),
    ( 2,  34, "Arena Master's Marchers", "Satanic"),
    ( 2,  35, "Satan's Molten Steps", "Set"),
    ( 2,  36, "Pearlescent Dream", "Heroic"),
    ( 2,  37, "Mana-Woven Walkers", "Satanic"),
    ( 2,  38, "Whisper Walker's Feiyue", "Satanic"),
    ( 2,  39, "Voodoo Stompers", "Satanic"),
    ( 2,  40, "Grand Wizard's Silk Shoes", "Satanic"),
    ( 2,  41, "Lava Treaders", "Satanic"),
    ( 2,  42, "Deep Chilled Marchers", "Satanic"),
    ( 2,  43, "Wind Walker's Step", "Heroic"),
    ( 2,  44, "Arch Wizard's Silk Boots", "Satanic"),
    ( 2,  45, "Chronomancer's Omnipotence", "Set"),
    ( 2,  46, "Ymir's Freezing Boots", "Set"),
    ( 2,  47, "Einar's Icy Stride", "Set"),
    ( 2,  48, "Grimbone's Marchers", "Heroic"),
    ( 2,  49, "Aetherflow Treads", "Satanic"),
    ( 2,  50, "Runescribe's Striders", "Satanic"),
    ( 2,  51, "Pla-Yer's Choice", "Satanic"),
    ( 2,  52, "Mos'Arathim's Kicks", "Satanic"),
    ( 2,  53, "Stalwart Sabatons", "Satanic"),
    ( 2,  54, "Onslaught Stompers", "Satanic"),
    ( 2,  55, "Mystic Soles", "Satanic"),
    ( 2,  56, "Enigma's Riftwalkers", "Satanic"),
    ( 2,  57, "Vipermagi's Sprinters", "Satanic"),
    ( 2,  58, "Tarek's Tradeoff", "Satanic"),
    ( 2,  59, "Lunar Prophet's Walkers", "Set"),
    ( 2,  60, "Soulflaming Marchers", "Heroic"),
    ( 2,  61, "Arc's Walkers", "Set"),
    ( 2,  62, "Marcher's of Hatred", "Unholy"),
    ( 2,  63, "Thunder Caller's Treads", "Set"),
    ( 2,  64, "Steampowered Flamewalkers", "Heroic"),
    ( 2,  65, "DEVELOPRE BOOT", "Unholy"),
    ( 2,  66, "Stranded Boot", "Heroic"),
    ( 2,  67, "Rocket Boots", "Satanic"),
    ( 2,  68, "Fumacinha's Favela Flipflop", "Heroic"),
    ( 2,  69, "Chaoswalkers", "Heroic"),
    ( 2,  70, "Thunder Roamers", "Heroic"),
    ( 2,  71, "Venom Roamers", "Heroic"),
    ( 2,  72, "Chilling Roamers", "Heroic"),
    ( 2,  73, "Scorching Roamers", "Heroic"),
    ( 2,  74, "Astral Roamers", "Heroic"),
    ( 2,  75, "Brutal Roamers", "Heroic"),
    ( 2,  76, "Metal Vocalist's War Boots", "Set"),
    ( 2,  77, "Desert's Storm", "Heroic"),
    ( 2,  78, "Adamant Roamers", "Heroic"),
    ( 2,  79, "Peg Leg", "Unholy"),
    ( 2,  80, "Rift Vectors", "Heroic"),
    # h3=3 Armas
    ( 3,   0, "Godfather", "Satanic"),
    ( 3,   0, "Death's Mirror", "Satanic"),
    ( 3,   0, "Dragon Knight's Flail", "Satanic"),
    ( 3,   0, "Inferno Slayer", "Satanic"),
    ( 3,   0, "Storm Fury", "Angelic"),
    ( 3,   0, "Odin's Battle Spear", "Satanic"),
    ( 3,   0, "Sawgun", "Satanic"),
    ( 3,   0, "The Iris", "Satanic"),
    ( 3,   0, "Blood of Abaddon", "Heroic"),
    ( 3,   0, "Oculus of Ages", "Heroic"),
    ( 3,   0, "God's Benevolence", "Satanic"),
    ( 3,   0, "Spellshard", "Satanic"),
    ( 3,   0, "Buriza-ko-nu", "Satanic"),
    ( 3,   0, "RT XQC-4910", "Satanic"),
    ( 3,   0, "Cobra Blood Vial", "Satanic"),
    ( 3,   0, "Wakayka's Tomahawk", "Satanic"),
    ( 3,   0, "Lemon", "Satanic"),
    ( 3,   1, "Jade Warrior's Gladius", "Satanic"),
    ( 3,   1, "Molten Dagger", "Satanic"),
    ( 3,   1, "Gurag's Stone Crusher", "Set"),
    ( 3,   1, "Rift Commander's Axe", "Satanic"),
    ( 3,   1, "Molten Paw", "Satanic"),
    ( 3,   1, "Crusader Halberd", "Satanic"),
    ( 3,   1, "Doublesaw 4000", "Satanic"),
    ( 3,   1, "Staff of Nether Flame", "Satanic"),
    ( 3,   1, "The Eye of Tarethiel", "Heroic"),
    ( 3,   1, "Clafaxier", "Satanic"),
    ( 3,   1, "Satan's Unholy Bible", "Satanic"),
    ( 3,   1, "Dragon's Breath", "Satanic"),
    ( 3,   1, "Wind's Force", "Satanic"),
    ( 3,   1, "Vampire Hunter", "Satanic"),
    ( 3,   1, "Ancient Mucus", "Satanic"),
    ( 3,   1, "Scarred Battle Darts", "Heroic"),
    ( 3,   1, "Fishing Rod", "Satanic"),
    ( 3,   2, "Storm Katana", "Satanic"),
    ( 3,   2, "Icy Shank", "Satanic"),
    ( 3,   2, "Nobunaga's Battle Slicer", "Set"),
    ( 3,   2, "Odin's Battle Axe", "Satanic"),
    ( 3,   2, "Hemorrhage", "Satanic"),
    ( 3,   2, "Death's Scythe", "Set"),
    ( 3,   2, "Doomsaw", "Satanic"),
    ( 3,   2, "Archangel Staff", "Satanic"),
    ( 3,   2, "Crystal Cane of Ice", "Satanic"),
    ( 3,   2, "Steve's Wand of Fortune", "Set"),
    ( 3,   2, "Book of Revelations", "Satanic"),
    ( 3,   2, "Wormclaw", "Satanic"),
    ( 3,   2, "Poison Ivy", "Satanic"),
    ( 3,   2, "Flamecannon", "Satanic"),
    ( 3,   2, "Demon Blood Flask", "Satanic"),
    ( 3,   2, "Mimir's Corrupted Axe", "Satanic"),
    ( 3,   2, "Voided Item", "Satanic"),
    ( 3,   3, "Molten Sword", "Satanic"),
    ( 3,   3, "Darkness", "Satanic"),
    ( 3,   3, "Gladiator's Wrecking Ball", "Set"),
    ( 3,   3, "Viking's Sacred Axe", "Set"),
    ( 3,   3, "Yoshi's Throat-Cutters", "Satanic"),
    ( 3,   3, "Shadow Carver", "Heroic"),
    ( 3,   3, "Vorpal Sharktooth", "Satanic"),
    ( 3,   3, "Raise of the Dead", "Satanic"),
    ( 3,   3, "Cane of the Tundra", "Satanic"),
    ( 3,   3, "St. HouDeanii's Tiny Fire Rod", "Angelic"),
    ( 3,   3, "Damien's Head", "Set"),
    ( 3,   3, "Hypothermia", "Heroic"),
    ( 3,   3, "Glimmerfury", "Satanic"),
    ( 3,   3, "Warbringer", "Satanic"),
    ( 3,   3, "Spirit Urn", "Satanic"),
    ( 3,   3, "Imperial Glaive", "Satanic"),
    ( 3,   4, "The Undying", "Satanic"),
    ( 3,   4, "Sand Dagger", "Satanic"),
    ( 3,   4, "Sacred Whip", "Satanic"),
    ( 3,   4, "Crystal Infused Axe", "Satanic"),
    ( 3,   4, "Elemental Claws", "Satanic"),
    ( 3,   4, "Poseidon's Might", "Satanic"),
    ( 3,   4, "The Annihilator", "Satanic"),
    ( 3,   4, "Apocalypto", "Satanic"),
    ( 3,   4, "St. Nimo's Lightbringer", "Angelic"),
    ( 3,   4, "Beacon of Shadows", "Heroic"),
    ( 3,   4, "Zealot's Book of Prophecy", "Set"),
    ( 3,   4, "Flamebringer", "Satanic"),
    ( 3,   4, "Jack", "Satanic"),
    ( 3,   4, "Doctor's Potion", "Set"),
    ( 3,   4, "Ukko's Revenge", "Heroic"),
    ( 3,   5, "Shattered Dimensions", "Satanic"),
    ( 3,   5, "Thunder Dagger", "Satanic"),
    ( 3,   5, "Nightmare Slasher", "Satanic"),
    ( 3,   5, "St. Rexis Sundering Axe", "Angelic"),
    ( 3,   5, "Talons of Wisdom", "Satanic"),
    ( 3,   5, "Vanguard's Lance", "Satanic"),
    ( 3,   5, "St. Draxis Longsaw", "Angelic"),
    ( 3,   5, "Ancient Sun Beacon", "Satanic"),
    ( 3,   5, "Pagan God's Blasphemy", "Heroic"),
    ( 3,   5, "Crystal Infused Wand", "Satanic"),
    ( 3,   5, "Solar Prophet's Tablet", "Set"),
    ( 3,   5, "Steve's Punchbow", "Set"),
    ( 3,   5, "Fred", "Satanic"),
    ( 3,   5, "Doomweed Vial", "Satanic"),
    ( 3,   5, "Wargod's Wrath", "Satanic"),
    ( 3,   6, "Ashbringer", "Satanic"),
    ( 3,   6, "Riftmaster's Dirge", "Heroic"),
    ( 3,   6, "Frozen Carver", "Satanic"),
    ( 3,   6, "Gem King's Cleaver", "Heroic"),
    ( 3,   6, "Earth Shaper's Talons", "Set"),
    ( 3,   6, "War God's Lance", "Satanic"),
    ( 3,   6, "Lumberjack's Chainsaw", "Set"),
    ( 3,   6, "Thorn of Helheim", "Set"),
    ( 3,   6, "Crackling Thunder", "Heroic"),
    ( 3,   6, "Uabel's Wand", "Set"),
    ( 3,   6, "Sands of Time", "Satanic"),
    ( 3,   6, "St. Soloyolo's Holy Bow", "Angelic"),
    ( 3,   6, "Steve's Bang", "Set"),
    ( 3,   6, "St. Neri's Rainbow Lance", "Angelic"),
    ( 3,   7, "Hiyoki's Vorpal Katana", "Satanic"),
    ( 3,   7, "Ceremonial Dagger", "Satanic"),
    ( 3,   7, "Unholy God's Flail", "Satanic"),
    ( 3,   7, "Winter's Bite", "Heroic"),
    ( 3,   7, "Spirit Walker's Guide", "Satanic"),
    ( 3,   7, "Jousting Lance", "Satanic"),
    ( 3,   7, "Candy Shredder", "Heroic"),
    ( 3,   7, "Flame of the Phoenix", "Satanic"),
    ( 3,   7, "Cane of Creation", "Heroic"),
    ( 3,   7, "Battle Mage's Wand", "Satanic"),
    ( 3,   7, "Book of Cold Death", "Heroic"),
    ( 3,   7, "Marksman's Hunting Bow", "Set"),
    ( 3,   7, "Chills of War", "Satanic"),
    ( 3,   7, "Serpent's Tooth", "Heroic"),
    ( 3,   8, "Hanzo's Flaming Katana", "Satanic"),
    ( 3,   8, "Fenrir's Bloodfang", "Heroic"),
    ( 3,   8, "Molten Hammer", "Satanic"),
    ( 3,   8, "Wraith Forged Cleaver", "Heroic"),
    ( 3,   8, "Glacier Talons", "Heroic"),
    ( 3,   8, "Golden God's Gladius", "Satanic"),
    ( 3,   8, "Royal Decapitator", "Satanic"),
    ( 3,   8, "Spell Eater", "Heroic"),
    ( 3,   8, "Voodoo Magician's Skull", "Satanic"),
    ( 3,   8, "Damien's Corrupted Head", "Heroic"),
    ( 3,   8, "Shadowfury", "Heroic"),
    ( 3,   8, "Commander's Sentry Blaster", "Angelic"),
    ( 3,   8, "Crystal Infused Javelin", "Satanic"),
    ( 3,   9, "Genji's Sword of Fate", "Set"),
    ( 3,   9, "Icy Crusher", "Satanic"),
    ( 3,   9, "Aurelion Fury", "Angelic"),
    ( 3,   9, "St. Draxis' Pigstick", "Angelic"),
    ( 3,   9, "Diablo", "Heroic"),
    ( 3,   9, "Necrobutcher's Curse", "Satanic"),
    ( 3,   9, "Wraithbone", "Satanic"),
    ( 3,   9, "Electro", "Satanic"),
    ( 3,   9, "Marine's Buddy", "Satanic"),
    ( 3,   9, "Valkyrie's Thunder Javelin", "Set"),
    ( 3,  10, "Wind Guardian's Gladius", "Satanic"),
    ( 3,  10, "The Light of Dawn", "Heroic"),
    ( 3,  10, "Abomination's Gut Ripper", "Satanic"),
    ( 3,  10, "Lancer's Glory", "Set"),
    ( 3,  10, "Eden's Harvester", "Heroic"),
    ( 3,  10, "Crow's Whisper", "Heroic"),
    ( 3,  10, "Clafaxier's Legacy", "Heroic"),
    ( 3,  10, "Hellspawn Eradicator", "Satanic"),
    ( 3,  10, "Demon", "Set"),
    ( 3,  10, "Deep Sea Glaive", "Satanic"),
    ( 3,  11, "Sand Crusader's Scimitar", "Satanic"),
    ( 3,  11, "Gladiator's Skullcrusher", "Satanic"),
    ( 3,  11, "Headsman's Bloodthirster", "Heroic"),
    ( 3,  11, "Champion's Flag Lance", "Set"),
    ( 3,  11, "Manafunneler's Conjurer", "Heroic"),
    ( 3,  11, "Deathquill", "Heroic"),
    ( 3,  11, "Sowyer's Javelin of Devastation", "Heroic"),
    ( 3,  12, "Azure's Wrath", "Satanic"),
    ( 3,  12, "Sung Lee's Destroyer Flail", "Heroic"),
    ( 3,  12, "Doom Cutter", "Satanic"),
    ( 3,  12, "Dark Knight's Lance", "Heroic"),
    ( 3,  12, "Witch's Wand", "Satanic"),
    ( 3,  12, "Recurving Corrosion", "Heroic"),
    ( 3,  12, "Crystal Infused Pistol", "Satanic"),
    ( 3,  12, "Sidewinder", "Heroic"),
    ( 3,  13, "Holy Warrior's Phase Blade", "Satanic"),
    ( 3,  13, "Revenant's Lasher", "Satanic"),
    ( 3,  13, "Brimskull Trident", "Heroic"),
    ( 3,  13, "St. Amitiel's Truth", "Angelic"),
    ( 3,  13, "F4-Tactical Rifle", "Satanic"),
    ( 3,  14, "Steve's Mighty Sword", "Set"),
    ( 3,  14, "Pillar of Niflheim", "Satanic"),
    ( 3,  14, "Thorn of Noxus", "Heroic"),
    ( 3,  14, "Astral Projector", "Heroic"),
    ( 3,  14, "Dreadnought", "Heroic"),
    ( 3,  15, "St. Gabriel's Retribution", "Angelic"),
    ( 3,  15, "Spiritus", "Satanic"),
    ( 3,  15, "Arachno Phobia", "Heroic"),
    ( 3,  15, "AK-47", "Heroic"),
    ( 3,  16, "Thor's Battle Sword", "Set"),
    ( 3,  16, "Monsoon", "Heroic"),
    ( 3,  16, "Glock 22", "Unholy"),
    ( 3,  17, "Nomad's Sandslicer", "Set"),
    ( 3,  17, "Rakhul's Legion Crusher", "Heroic"),
    ( 3,  17, "Arrow of Niflheim", "Heroic"),
    ( 3,  17, "Dracula's Demise", "Heroic"),
    ( 3,  18, "Dante's Demon Blade", "Set"),
    ( 3,  18, "The Dawn Bringer", "Angelic"),
    ( 3,  18, "Eternity", "Heroic"),
    ( 3,  18, "Master's Magnum", "Heroic"),
    ( 3,  19, "Masamune", "Set"),
    ( 3,  19, "Luci's Day", "Heroic"),
    ( 3,  19, "Arrow of Zamjo", "Heroic"),
    ( 3,  20, "Muramasa", "Set"),
    ( 3,  20, "Shishkebab", "Heroic"),
    ( 3,  20, "Phantom Strike", "Heroic"),
    ( 3,  21, "Crystal Infused Sword", "Satanic"),
    ( 3,  21, "Stormslayer", "Unholy"),
    ( 3,  22, "Bonetti's Rapier", "Heroic"),
    ( 3,  22, "Pit Fighter's Skullcracker", "Set"),
    ( 3,  23, "Eternal Glaive", "Satanic"),
    ( 3,  23, "Pit Fighter's Brutalizer", "Set"),
    ( 3,  24, "Metal Vocalist's Warlock", "Set"),
    ( 3,  25, "Sanguine Blade", "Satanic"),
    ( 3,  26, "Gut's BFS", "Satanic"),
    ( 3,  27, "Gut's HFS", "Satanic"),
    ( 3,  28, "Grimbone's Scythe", "Heroic"),
    ( 3,  29, "Arch Angel's Phase Blade", "Heroic"),
    ( 3,  30, "Daisy", "Set"),
    ( 3,  31, "Gabriel's Broken Resolve", "Heroic"),
    ( 3,  32, "The Hope Ender", "Heroic"),
    ( 3,  33, "Glowstick Estoc", "Heroic"),
    ( 3,  34, "Blood Moon Crescent", "Heroic"),
    ( 3,  35, "Stofflix Cooking Cleaver", "Unholy"),
    ( 3,  37, "Phantom Scimitar", "Heroic"),
    # h3=4 Luvas
    ( 4,   0, "Shadow's Grasp", "Satanic"),
    ( 4,   1, "Midas' Hands", "Heroic"),
    ( 4,   2, "Scuttle Crab Gauntlets", "Satanic"),
    ( 4,   3, "Warmaster's Tribal Paws", "Satanic"),
    ( 4,   4, "Death's Grasp", "Set"),
    ( 4,   5, "Anubis' Mighty Hands", "Set"),
    ( 4,   6, "Mevius' Mighty Gauntlets", "Set"),
    ( 4,   7, "Throat Cutters", "Satanic"),
    ( 4,   8, "Thor's Battle Gloves", "Set"),
    ( 4,   9, "Nomad's Sand Mitts", "Set"),
    ( 4,  10, "Marksman's Hunting Gloves", "Set"),
    ( 4,  11, "Doctor's Grasp", "Set"),
    ( 4,  12, "Dante's Mitts", "Set"),
    ( 4,  13, "Lancers Gauntlets", "Set"),
    ( 4,  14, "Devil's Grasp", "Set"),
    ( 4,  15, "Gloves of Wilderness", "Set"),
    ( 4,  16, "Hands of Flame", "Set"),
    ( 4,  17, "Conjurer Mitts", "Satanic"),
    ( 4,  18, "Zealot's Deathbringers", "Set"),
    ( 4,  19, "Bone Conjurer's Grips", "Set"),
    ( 4,  20, "Lumberjack's Safety Gloves", "Set"),
    ( 4,  21, "Blood-letter's Plated Gauntlet", "Set"),
    ( 4,  22, "Venom's Talons", "Set"),
    ( 4,  23, "Champion's Fighting Gloves", "Set"),
    ( 4,  24, "Lost Master's Gauntlets", "Set"),
    ( 4,  25, "Brawler's Fighting Mitts", "Heroic"),
    ( 4,  26, "Shadow Occultist's Wraps", "Heroic"),
    ( 4,  27, "Razor Knuckles", "Satanic"),
    ( 4,  28, "Siege Breakers", "Satanic"),
    ( 4,  29, "Spellweavers", "Heroic"),
    ( 4,  30, "St. Ahto's Diamond Hands", "Angelic"),
    ( 4,  31, "Uabel's Gloves", "Set"),
    ( 4,  32, "Battle Worn Gauntlets", "Set"),
    ( 4,  33, "Wisdom's Hold", "Satanic"),
    ( 4,  34, "Imbued Mage Gloves", "Satanic"),
    ( 4,  35, "Battle Caster's Gauntlets", "Satanic"),
    ( 4,  36, "Plated Crimson Defenders", "Satanic"),
    ( 4,  37, "Sand Manipulator's Authority", "Set"),
    ( 4,  38, "Einar's Padded Gauntlets", "Set"),
    ( 4,  39, "Rapidcaster Mitts", "Satanic"),
    ( 4,  40, "Lifeward Gauntlets", "Satanic"),
    ( 4,  41, "Venomburned Gauntlets", "Satanic"),
    ( 4,  42, "Sorcerer's Surge Grips", "Satanic"),
    ( 4,  43, "Shinobi's Deadwraps", "Satanic"),
    ( 4,  44, "Vigorous Lifegrips", "Satanic"),
    ( 4,  45, "Titan's Staticguards", "Satanic"),
    ( 4,  46, "Thorned Wristguards", "Satanic"),
    ( 4,  47, "Demonweaver's Heralds", "Satanic"),
    ( 4,  48, "Rakhul's Stone Hands", "Heroic"),
    ( 4,  49, "Demonfire Accelerators", "Unholy"),
    ( 4,  50, "Ali's Boxing Gloves", "Heroic"),
    ( 4,  51, "Fighter Magi's Grips", "Heroic"),
    ( 4,  52, "Necrocaller's Grips", "Heroic"),
    ( 4,  53, "Grasp of the Phoenix", "Heroic"),
    ( 4,  54, "Arcanum Asphyxiators", "Heroic"),
    ( 4,  55, "Tectonic Grips", "Heroic"),
    ( 4,  56, "Frostbitten Necrosis", "Heroic"),
    ( 4,  57, "Manahungerers", "Heroic"),
    ( 4,  58, "Rimskin Assassins", "Heroic"),
    ( 4,  59, "Plague Bringer's Touch", "Heroic"),
    ( 4,  60, "Pit Fighter's Bone Crushers", "Set"),
    ( 4,  61, "Shade of Sand", "Satanic"),
    ( 4,  62, "Death Knight's Gauntlets", "Heroic"),
    ( 4,  63, "Chronobreakers", "Heroic"),
    ( 4,  64, "Skinwalker's Paw", "Set"),
    ( 4,  65, "Infected Grasp", "Heroic"),
    # h3=5 Colar
    ( 5,   0, "All Seeing Eye", "Satanic"),
    ( 5,   1, "High Demon's Necklace", "Satanic"),
    ( 5,   2, "Satan's Precious", "Set"),
    ( 5,   3, "Shining Pearl", "Satanic"),
    ( 5,   4, "Gurag's Pebble", "Set"),
    ( 5,   5, "Anubis Oculus", "Set"),
    ( 5,   6, "Tal's Pendant", "Set"),
    ( 5,   7, "Damien's Soulstone", "Set"),
    ( 5,   8, "Steve's Necklace", "Set"),
    ( 5,   9, "Baby Log Necklace", "Satanic"),
    ( 5,  10, "Treasure Pendant", "Satanic"),
    ( 5,  11, "Ritual Pendant", "Satanic"),
    ( 5,  12, "Nobunaga's Warrior Spirit", "Set"),
    ( 5,  13, "Visage's Eye", "Satanic"),
    ( 5,  14, "Elder's Heart", "Satanic"),
    ( 5,  15, "Devil's Gem", "Set"),
    ( 5,  16, "Aztec Necklace", "Set"),
    ( 5,  17, "Sacred Pendant", "Set"),
    ( 5,  18, "Spirit Pendant", "Set"),
    ( 5,  19, "Rift Warrior's Skull", "Satanic"),
    ( 5,  20, "Raven's Claw", "Satanic"),
    ( 5,  21, "Eye of Horus", "Satanic"),
    ( 5,  22, "Pyramid Pendant", "Satanic"),
    ( 5,  23, "Storm Pendant", "Satanic"),
    ( 5,  24, "Traveler's Compass", "Set"),
    ( 5,  25, "Pendant of Eternity", "Heroic"),
    ( 5,  26, "Juggernaut's Emblem", "Set"),
    ( 5,  27, "Engineer's Master Pendant", "Set"),
    ( 5,  28, "Bone Conjurer's Mask", "Set"),
    ( 5,  29, "Venom's Necklace", "Set"),
    ( 5,  30, "Champion's Medal of Valor", "Set"),
    ( 5,  31, "Plunderer's Spy Glass", "Set"),
    ( 5,  32, "Kallik's Fury", "Satanic"),
    ( 5,  33, "Unfathomable Puzzle", "Satanic"),
    ( 5,  34, "Philosopher's Stone", "Heroic"),
    ( 5,  35, "Charcoal Memento", "Satanic"),
    ( 5,  36, "Coldfire Amulet", "Satanic"),
    ( 5,  37, "Serpentine Necklace", "Satanic"),
    ( 5,  38, "Compass of Wealth", "Heroic"),
    ( 5,  39, "Dark Lord's Sigil", "Satanic"),
    ( 5,  40, "Lost Dieties Authority", "Satanic"),
    ( 5,  41, "Thunderstone Amulet", "Satanic"),
    ( 5,  42, "Earth Goliath's Protection", "Satanic"),
    ( 5,  43, "Claw of the Bloodthirsty", "Satanic"),
    ( 5,  44, "Arcana Eye", "Satanic"),
    ( 5,  45, "Scout's Medal of Honor", "Satanic"),
    ( 5,  46, "Claw of the Hunter", "Satanic"),
    ( 5,  47, "Amethyst Knight's Amulet", "Satanic"),
    ( 5,  48, "Chronomancer's Curio of Time", "Set"),
    ( 5,  49, "Ymir's Frozen Tear", "Set"),
    ( 5,  50, "Insignia of the Hunter", "Set"),
    ( 5,  51, "Lifeblood Infuser", "Satanic"),
    ( 5,  52, "Arcane Slayer's Talisman", "Satanic"),
    ( 5,  53, "Rapidshell Medallion", "Satanic"),
    ( 5,  54, "Soulreplenish Pendant", "Satanic"),
    ( 5,  55, "Eagerblade's Tooth", "Satanic"),
    ( 5,  56, "Coldsnap Insignia", "Satanic"),
    ( 5,  57, "Insignia of the Burning Legion", "Satanic"),
    ( 5,  58, "Gambler's Demise", "Satanic"),
    ( 5,  59, "Stone of Archaeology", "Satanic"),
    ( 5,  60, "Tarethiel's Fall", "Heroic"),
    ( 5,  61, "Amulet of Colosseum", "Heroic"),
    ( 5,  62, "Lilith's Scorn", "Unholy"),
    ( 5,  63, "Arc's Sigil", "Set"),
    ( 5,  64, "Light Bringer's Mark", "Satanic"),
    ( 5,  65, "Gryphon's Claw", "Heroic"),
    ( 5,  66, "Eagle's Claw", "Heroic"),
    ( 5,  67, "Thoth's Agony", "Heroic"),
    ( 5,  68, "Metal Vocalist's Pentagram", "Set"),
    ( 5,  69, "Dragon's Eye", "Heroic"),
    ( 5,  70, "Signet of Kadosh", "Heroic"),
    ( 5,  71, "Shadow Beacon", "Heroic"),
    ( 5,  72, "Fractal of Existence", "Heroic"),
    ( 5,  73, "Prophet's Foliage", "Set"),
    ( 5,  74, "Skinwalker's Claw", "Set"),
    ( 5,  76, "Blood Maggot Pendant", "Heroic"),
    # h3=6 Escudo
    ( 6,   0, "Ancient Aegis", "Heroic"),
    ( 6,   1, "Tombstone", "Heroic"),
    ( 6,   2, "Rift Eye", "Satanic"),
    ( 6,   3, "Demon's Mirror", "Heroic"),
    ( 6,   4, "The Templar", "Satanic"),
    ( 6,   5, "Lancer's Wall", "Satanic"),
    ( 6,   6, "Shadow Buckler", "Satanic"),
    ( 6,   7, "Wall of the Legion", "Satanic"),
    ( 6,   8, "SUOMI FINLAND PERKELE", "Heroic"),
    ( 6,   9, "Den Glider In", "Satanic"),
    ( 6,  10, "Gladiator's Wall", "Set"),
    ( 6,  11, "Sacred Aegis", "Set"),
    ( 6,  12, "Aztec Ward", "Set"),
    ( 6,  13, "Ward of Toxicity", "Satanic"),
    ( 6,  14, "Storm Gladiator's Wall", "Satanic"),
    ( 6,  15, "Thunder Lord's Aegis", "Satanic"),
    ( 6,  16, "Crystal Infused Shield", "Satanic"),
    ( 6,  17, "Vagabond's Ward", "Set"),
    ( 6,  18, "Flame Diviner's Ward", "Set"),
    ( 6,  19, "Justiciar's Thunder Wall", "Set"),
    ( 6,  20, "Shield Bearer's Wall", "Set"),
    ( 6,  21, "Valkyrie's Battle Shield", "Set"),
    ( 6,  22, "Leprechauns Greed", "Satanic"),
    ( 6,  23, "Gem Encrusted Tower", "Satanic"),
    ( 6,  24, "Pandemic Shield", "Satanic"),
    ( 6,  25, "Iron Giants Shield", "Satanic"),
    ( 6,  26, "St. Tomi's Vibrant Aura", "Angelic"),
    ( 6,  27, "Defender's Justice", "Heroic"),
    ( 6,  28, "Shield of the Abyss", "Heroic"),
    ( 6,  29, "Mirror of Flesh", "Satanic"),
    ( 6,  30, "St. Hallgar's Bloodforged Aegis", "Angelic"),
    ( 6,  31, "Ward of Blood", "Satanic"),
    ( 6,  32, "Novice's Tower", "Satanic"),
    ( 6,  33, "King's Tower Shield", "Satanic"),
    ( 6,  34, "Heaven's Champion", "Satanic"),
    ( 6,  35, "Pitfiend's Thorn", "Satanic"),
    ( 6,  36, "Celestial's Authority", "Heroic"),
    ( 6,  37, "Visage of Relentless Rage", "Satanic"),
    ( 6,  38, "Battle Mage's Shield", "Satanic"),
    ( 6,  39, "Darkwood Defender", "Satanic"),
    ( 6,  40, "Rusted Spiked Shield", "Satanic"),
    ( 6,  41, "Blessed Defender", "Satanic"),
    ( 6,  42, "Thunderburn Aegis", "Satanic"),
    ( 6,  43, "Shield of Shattered Elements", "Satanic"),
    ( 6,  44, "Battlemagi's Rampart", "Satanic"),
    ( 6,  45, "Archmagus Glyphward", "Satanic"),
    ( 6,  46, "Lost Wizard's Barrier", "Satanic"),
    ( 6,  47, "Bob's Piece of Plywood", "Satanic"),
    ( 6,  48, "Thunderstruck Deflector", "Satanic"),
    ( 6,  49, "Rendguard of Carnage", "Satanic"),
    ( 6,  50, "Spellbinder's Magebarrier", "Satanic"),
    ( 6,  51, "Gabriel's Unholy Oath", "Heroic"),
    ( 6,  52, "Pit Ravager's Cetratus", "Heroic"),
    ( 6,  53, "SUOMI FINLAND SUATANA", "Satanic"),
    ( 6,  54, "Shadow Lantern", "Heroic"),
    ( 6,  55, "The Event Horizon", "Heroic"),
    ( 6,  56, "Overgrowth", "Heroic"),
    # h3=7 Anel
    ( 7,   0, "Ra's Band", "Heroic"),
    ( 7,   1, "Molten Ring", "Satanic"),
    ( 7,   2, "Dragonsteel Ring", "Satanic"),
    ( 7,   3, "Stone of Premonition", "Heroic"),
    ( 7,   4, "Khodo's Wedding Band", "Satanic"),
    ( 7,   5, "Demon Eye Ring", "Satanic"),
    ( 7,   6, "Satanic Eye", "Satanic"),
    ( 7,   7, "Giant's Band of Strength", "Heroic"),
    ( 7,   8, "Iron Ring of Prometheus", "Satanic"),
    ( 7,   9, "St. Aaron's Eternal Rage", "Angelic"),
    ( 7,  10, "Elven Grace", "Satanic"),
    ( 7,  11, "Quickening Zephyr", "Heroic"),
    ( 7,  12, "Mana Bender's Will", "Heroic"),
    ( 7,  13, "Tectonic Frequency", "Satanic"),
    ( 7,  14, "Fury of Tarethiel", "Angelic"),
    ( 7,  15, "The Absence of Constraint", "Heroic"),
    ( 7,  16, "Mark of Ferocity", "Satanic"),
    ( 7,  17, "Sanguine Bloodstone", "Satanic"),
    ( 7,  18, "Archer's Story", "Satanic"),
    ( 7,  19, "Onyx Slayer's Band", "Satanic"),
    ( 7,  20, "Templar's Faith", "Satanic"),
    ( 7,  21, "Soulforged Ring", "Heroic"),
    ( 7,  23, "Sung Lee's Unleashed Rage", "Heroic"),
    ( 7,  24, "Apex Striker's Ring", "Satanic"),
    ( 7,  25, "Swiftsoul Band", "Satanic"),
    ( 7,  26, "Soul Funneling Loop", "Satanic"),
    ( 7,  27, "Colossus Circle of Vitality", "Satanic"),
    ( 7,  28, "Viper's Seal of Corrosion", "Satanic"),
    ( 7,  29, "Astrope's Signed of Blessing", "Satanic"),
    ( 7,  30, "Ring of the Cowraven", "Satanic"),
    ( 7,  31, "Circle of Nature", "Satanic"),
    ( 7,  32, "Merlock's Halo", "Satanic"),
    ( 7,  33, "Ring of Tallus", "Satanic"),
    ( 7,  34, "Solar Prophet's Signet", "Set"),
    ( 7,  35, "Lunar Prophet's Band", "Set"),
    ( 7,  36, "Rakhul's Ritual Band", "Heroic"),
    ( 7,  38, "Signet of Harbringer", "Heroic"),
    ( 7,  39, "Hellfire Halo", "Heroic"),
    ( 7,  40, "Signet of Corruption", "Heroic"),
    ( 7,  41, "Arcanis", "Heroic"),
    ( 7,  42, "Azazel's Despair", "Heroic"),
    ( 7,  43, "Emblem of the Daemon", "Heroic"),
    ( 7,  44, "Stormloop", "Heroic"),
    ( 7,  45, "Hero Siege Enjoyer", "Heroic"),
    ( 7,  46, "Pit Fighter's Carnage", "Set"),
    ( 7,  47, "Metal Vocalist's Fame", "Set"),
    ( 7,  48, "Scourge Loop", "Heroic"),
    ( 7,  49, "Dragon's Blessing", "Heroic"),
    ( 7,  50, "Cursed Artifact", "Satanic"),
    ( 7,  51, "Signet of Shadows", "Heroic"),
    ( 7,  52, "The Downfall of Felps", "Heroic"),
    ( 7,  53, "Orbital Loop", "Satanic"),
    ( 7,  54, "Hellspawn's Curse", "Satanic"),
    ( 7,  55, "Gargantuan's Soul", "Satanic"),
    ( 7,  56, "Void Bomba", "Heroic"),
    ( 7,  57, "Absolute Zero", "Unholy"),
    ( 7,  58, "Prophet's Pinecone", "Set"),
    ( 7,  59, "Skinwalker's Sigil", "Set"),
    ( 7,  61, "Parasite Loop", "Heroic"),
    # h3=8 Cinto
    ( 8,   0, "Tundra Warrior's Girdle", "Satanic"),
    ( 8,   1, "Vipermagi's Belt", "Satanic"),
    ( 8,   2, "Lich Sash", "Satanic"),
    ( 8,   3, "Tribal Belt", "Satanic"),
    ( 8,   4, "Foxweave Belt", "Satanic"),
    ( 8,   5, "Assassin's Belt", "Satanic"),
    ( 8,   6, "Crystal Belt", "Satanic"),
    ( 8,   7, "Heavy Duty", "Satanic"),
    ( 8,   8, "Commander's Sash", "Satanic"),
    ( 8,   9, "Monkeyskin Belt", "Satanic"),
    ( 8,  10, "Belt of War", "Satanic"),
    ( 8,  11, "Traveler's Double Belt", "Set"),
    ( 8,  12, "Belt of Skulls", "Heroic"),
    ( 8,  13, "Engineer's Toolbelt", "Set"),
    ( 8,  14, "Vagabond's Strap", "Set"),
    ( 8,  15, "Flame Diviner's Cord", "Set"),
    ( 8,  16, "Justiciar's Thunder Sash", "Set"),
    ( 8,  17, "Earth Shaper's Belt", "Set"),
    ( 8,  18, "Knight's Girdle", "Satanic"),
    ( 8,  19, "Belt of Infinite Wealth", "Heroic"),
    ( 8,  20, "Rugal's Sash of Undertaking", "Satanic"),
    ( 8,  21, "Sash of the Magi", "Satanic"),
    ( 8,  22, "Ice Queen's Cestus", "Satanic"),
    ( 8,  23, "Set's Lightning Sash", "Heroic"),
    ( 8,  24, "Tether of Anguish", "Satanic"),
    ( 8,  25, "Hatshepsut's Girdle", "Satanic"),
    ( 8,  26, "Ashen Belt", "Satanic"),
    ( 8,  27, "Combat Duty Belt", "Satanic"),
    ( 8,  28, "Cingulum of Shifting Destiny", "Satanic"),
    ( 8,  29, "Brute's Cord", "Satanic"),
    ( 8,  30, "Sun Wukong's Belt", "Satanic"),
    ( 8,  31, "Warbosses' Trophy Belt", "Satanic"),
    ( 8,  32, "Gaze of the Void", "Satanic"),
    ( 8,  33, "Pitfighter's Razor Belt", "Satanic"),
    ( 8,  34, "Bronze Legion Girdle", "Satanic"),
    ( 8,  35, "Girdle of Resilience", "Satanic"),
    ( 8,  36, "USB's Cord", "Satanic"),
    ( 8,  37, "Guardian's Waistband", "Satanic"),
    ( 8,  38, "Storm's Dawn", "Satanic"),
    ( 8,  39, "Runemaster's Waistwrap", "Satanic"),
    ( 8,  40, "Solar Magister's Sash", "Satanic"),
    ( 8,  41, "Lunar Prophet's Girdle", "Set"),
    ( 8,  42, "Sash of Eternal Hatred", "Heroic"),
    ( 8,  43, "Gladiator King's Belt", "Heroic"),
    ( 8,  44, "Majorie's Belt", "Angelic"),
    ( 8,  45, "Butcher's Belt", "Set"),
    ( 8,  46, "Thunder Caller's Sash", "Set"),
    ( 8,  47, "Soulburn Belt", "Heroic"),
    ( 8,  48, "Freya's Frozen Buckle", "Heroic"),
    ( 8,  49, "Komodo's Bloodstrap", "Heroic"),
    ( 8,  50, "Trophy Hunter", "Heroic"),
    ( 8,  51, "Liquor Holster", "Angelic"),
    ( 8,  52, "Girdle of Eternal War", "Heroic"),
    ( 8,  54, "Sandmagi's Sash", "Satanic"),
    ( 8,  55, "Serpent's Embrace", "Heroic"),
    ( 8,  56, "Prophet's Branch", "Set"),
    # h3=10 Acessório
    (10,   0, "Raider's Torch", "Satanic"),
    (10,   1, "Eye of Skadi", "Satanic"),
    (10,   2, "Apple of Evolution", "Satanic"),
    (10,   3, "Moonshard", "Satanic"),
    (10,   4, "Solar Charm", "Satanic"),
    (10,   5, "Aztec Coin", "Satanic"),
    (10,   6, "Beetle of Life", "Satanic"),
    (10,   7, "Tal's Deathskull", "Set"),
    (10,   8, "Gurag's Heart Charm", "Set"),
    (10,   9, "Anubis' Ankh Charm", "Satanic"),
    (10,  10, "Damien's Cage", "Set"),
    (10,  11, "Satan's Chalice", "Satanic"),
    (10,  12, "Hello its me, Steve!", "Set"),
    (10,  13, "Redneck's Keychain", "Set"),
    (10,  14, "Pirate Captain's Flag", "Set"),
    (10,  15, "Death Lord's Zombie Head", "Set"),
    (10,  16, "Marksman's Quiver", "Set"),
    (10,  17, "Wind Token", "Satanic"),
    (10,  18, "Doctor's Mask in a Jar", "Set"),
    (10,  19, "Heart of Agony", "Set"),
    (10,  20, "Aztec Devil", "Set"),
    (10,  21, "Sacred Owl", "Set"),
    (10,  22, "Flaming Coin", "Set"),
    (10,  23, "Torch of Shadows", "Heroic"),
    (10,  24, "Traveler's Map Journal", "Set"),
    (10,  25, "Engineer's Mini Drone", "Set"),
    (10,  26, "Zealot's Beads of Destruction", "Set"),
    (10,  27, "Bone Conjurer's Trophy", "Set"),
    (10,  28, "Champion's Signet", "Set"),
    (10,  29, "Plunderer's Gunpowder Bag", "Set"),
    (10,  30, "Fulgurite", "Heroic"),
    (10,  31, "Loaded Dice", "Heroic"),
    (10,  32, "Annihilator", "Unholy"),
    (10,  33, "Bag of Unknown Riches", "Satanic"),
    (10,  34, "Spine Trophy", "Satanic"),
    (10,  35, "Cold Giant's Charm", "Satanic"),
    (10,  36, "Jack's Pumpkin Spice", "Satanic"),
    (10,  37, "Shrunken Head", "Satanic"),
    (10,  38, "Tarethiel's Ancient Wisdom", "Heroic"),
    (10,  39, "Sheep King's Wool", "Set"),
    (10,  40, "Viking's Glyphed Rune", "Satanic"),
    (10,  41, "Witches Claw", "Satanic"),
    (10,  42, "Adventurer's Quiver", "Satanic"),
    (10,  43, "Mark of the Black Knight", "Satanic"),
    (10,  44, "Hardened Steel Defender", "Satanic"),
    (10,  45, "Canopic Jar of Blood", "Set"),
    (10,  46, "Sundial of Ancient Worlds", "Set"),
    (10,  47, "Water Melon", "Angelic"),
    (10,  48, "Earth Melon", "Angelic"),
    (10,  49, "Fire Melon", "Angelic"),
    (10,  50, "Air Melon", "Angelic"),
    (10,  51, "Supreme Elemelon", "Angelic"),
    (10,  52, "Torstein's Anvil", "Heroic"),
    (10,  53, "Arcane Pumpkin", "Unholy"),
    (10,  54, "Rotten Pumpkin", "Unholy"),
    (10,  55, "Eye of Rakhul", "Heroic"),
    (10,  56, "Lilith's Wrath", "Unholy"),
    (10,  57, "Divine Crackpipe", "Angelic"),
    (10,  58, "Abomination's Heart", "Set"),
    (10,  59, "Abomination's Brain", "Set"),
    (10,  60, "Abomination's Eye", "Set"),
    (10,  61, "Plague Shot", "Heroic"),
    (10,  62, "Barrel of Explosives", "Set"),
    (10,  63, "The Detonator", "Set"),
    (10,  64, "Gas Canister", "Heroic"),
    (10,  65, "Forking Bolts", "Unholy"),
    (10,  66, "Reverse Card", "Angelic"),
    (10,  67, "Tablet of Awakening", "Heroic"),
    (10,  68, "Crow's Feather", "Satanic"),
    (10,  69, "Sassy's Dislocated Foot", "Satanic"),
    (10,  70, "Chaos Gemstone", "Heroic"),
    (10,  71, "Finger of Despair", "Heroic"),
    (10,  72, "Sobek's Fall", "Heroic"),
    (10,  73, "Graxy's Lucky Lure", "Heroic"),
    (10,  74, "The Almighty Nugget", "Angelic"),
    (10,  75, "Orange Grayon", "Heroic"),
    (10,  76, "Aimbot.exe", "Satanic"),
    (10,  77, "Storm In A Vial", "Heroic"),
    (10,  78, "Dev Charm Small", "Angelic"),
    (10,  81, "Dragon's Heart", "Heroic"),
    (10,  82, "Wizard's Dice", "Heroic"),
    (10,  83, "Gladiator's Dice", "Heroic"),
    (10,  84, "Bob's Grenade", "Set"),
    (10,  85, "Cursed Gyroscope", "Satanic"),
    (10,  86, "Mysterious Monkey Paw", "Set"),
    (10,  87, "Dibbik Box", "Set"),
    (10,  88, "Mystery Card", "Satanic"),
    (10,  89, "Overloaded Dice", "Unholy"),
    (10,  90, "Devil's Pact", "Unholy"),
    (10,  91, "Soul Collector", "Unholy"),
    (10,  92, "Tiny Planet", "Set"),
    (10,  93, "Telescope", "Set"),
    (10,  94, "Nomad's Rotten Corpse", "Heroic"),
    (10,  95, "Voodoo Doll", "Heroic"),
    (10,  96, "Bull's Eye", "Set"),
    (10,  97, "Sniper's Scope", "Set"),
    (10,  98, "Goburin's Head", "Unholy"),
]